docs: fix url to Chinese docs' url
ant-design/ant-design-pro-site pull request #551
Opened 2021-05-08 05:04 UTC by Ivocin

调整了中文文档中的 url 地址到对应的中文文档地址

2021-05-08 05:06 UTC, Ivocin commented on docs/layout.zh-CN.md
> -我们可以在 route 中进行 menu 相关配置，来决定当前路由是否会被渲染在菜单中。[详细配置说明](https://umijs.org/plugins/plugin-layout#menu)
在 umi 官网没有找到 menu 的 hash，是不是这块文档更新了，我暂时把 #menu 给去掉了
https://umijs.org/plugins/plugin-layout#menu

2021-05-10 16:02 UTC, aspirantzhang requested changes
有些地址没改对

2021-05-11 05:41 UTC, aspirantzhang approved these changes

2021-05-12 01:27 UTC, chenshuai2144 commented
优秀的同学

2021-05-12 01:27 UTC, merged